Use the more stable JWT.decode to extract 'kid'
envato/jwt_signed_request pull request #26
Opened 2018-06-12 13:44 UTC by chrisface

The API for `JWT.decoded_segments` has been moved around as well as the arguments. Instead we can use `JWT.decode` to get the same result which is the same across different versions of the jwt Gem.

All the tests are still passing against the latest version of the jwt Gem. I've not verified this against all other versions as I don't have apps running but it looks like this part of the API has been stable for a long time.

2018-06-12 22:43 UTC, twe4ked approved these changes
Thanks for the PR. This looks great 👍

2018-06-14 05:48 UTC, yoshdog commented on lib/jwt_signed_request/verify.rb
> +      _body, jwt_header = ::JWT.decode(jwt_token, nil, false, algorithm: "None")
Thanks for the PR, and yes using the `decode` method is a much better idea.

One small change is we can remove the `algorithm: "None"` from the argument list as we are not verifying it.

I tested it out and it returns the same thing 😄 

```
irb(main):003:0> jwt = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

irb(main):004:0> JWT.decode(jwt, nil, false)
=> [{"sub"=>"1234567890", "name"=>"John Doe", "iat"=>1516239022}, {"alg"=>"HS256", "typ"=>"JWT"}]
```

2018-06-14 05:48 UTC, yoshdog requested changes
One small change is we can remove the `algorithm: "None"` from the argument list as we are not verifying it, so its not needed.

2018-06-15 10:24 UTC, chrisface commented
Taken care of that now. Thanks for the quick turnaround 👍

2018-06-15 10:41 UTC, yoshdog approved these changes
looks good

2018-06-15 10:41 UTC, merged

2018-06-15 10:58 UTC, yoshdog commented
Just released and pushed v2.3.0 to rubygems

thanks again @chrisface